---
title: "R Notebook"
output: html_notebook
---
```{r}
# function that calculates annual compound interest
compound.interest <- function(p, i, y, t = 12, plotit = T, ...) {
  # checking for missing arguments
  if (missing(p) || missing(i) || missing(y)) {
    return("missing arguments: p, i, y are mandatory")
  }
  
  f <- p * (1 + i / (100 * t)) ^ (t * 1:y)
  
  if (plotit) {
    plot(1:y, f, type = "s", ...)
  } else {
    return(f)
  }
}

compound.interest(p = 100, i = 22.9, y = 20, ylab = "Balance (F)", xlab = "Year (y)")
compound.interest(p = 100, i = 22.9, y = 20, t = 1, ylab = "Balance (F)", xlab = "Year (y)")
```
```{r}
# function that takes a list of character vectors and append "!" after each element of each member
foo <- list("a", c("b", "c", "d", "e"), "f", c("g", "h", "i"))
lapply(foo, FUN = function(x) {paste(x, "!", sep = "")})
```
```{r}
# function that computes geometric mean of members of a list
# if member is a vector => compute mean of the vector
# if member is a matrix => compute mean of each row of the matrix

geom.mean <- function(li) {
  res <- list()
  counter <- 0
  
  geom.mean.help <- function(v) {
    return(prod(v) ^ (1/length(v)))
  }
  
  for (i in 1:length(li)) {
    counter <- counter + 1
    if (is.vector(li[[i]])) {
      res[[i]] <- geom.mean.help(li[[i]])
    } else {
      res[[i]] <- apply(li[[i]], MARGIN = 1, FUN = geom.mean.help)
    }
  }
  
  return(res)
}

foo <- list(1:3, matrix(c(3.3, 3.2, 2.8, 2.1, 4.6, 4.5, 3.1, 9.4), 4, 2),
            matrix(c(3.3, 3.2, 2.8, 2.1, 4.6, 4.5, 3.1, 9.4), 2, 4))
geom.mean(foo)
```
```{r}
bar <- list(1:9, matrix(1:9, 1, 9), matrix(1:9, 9, 1), matrix(1:9, 3, 3))
geom.mean(bar)
```