---
title: "R Notebook"
output: html_notebook
---
```{r}
demo.data <- data.frame(y = c(1.55, 0.42, 1.29, 0.73, 0.76, -1.09, 1.41, -0.32),
                        x1 = c(1.13, -0.73, 0.12, 0.52, -0.54, -1.15, 0.20, -1.09),
                        x2 = c(1, 0, 1, 1, 0, 1, 0, 1))
demo.data
```
```{r}
Y <- matrix(demo.data$y)
Y
```
```{r}
n <- nrow(demo.data)
X <- matrix(c(rep(1, n), demo.data$x1, demo.data$x2), ncol = 3)
X
```
```{r}
beta.hat <- solve(t(X) %*% X) %*% t(X) %*% Y
beta.hat
```
```{r}
demo.fit <- lm(y~x1+x2, data = demo.data)
summary(demo.fit)
```
```{r}
library(MASS)
head(survey)
```

```{r}
surv.fit <- lm(Height~Wr.Hnd+Sex, data = survey)
summary(surv.fit)
```
```{r}
summary(lm(Height~Wr.Hnd+Sex+Smoke, data = survey))
```
```{r}
(cf <- coef(lm(Height~Wr.Hnd+Sex, data = survey)))

plot(survey$Height~survey$Wr.Hnd, 
     col = c("grey", "black")[survey$Sex], pch = 20, cex = 1.25)
abline(a = cf[1], b = cf[2], col = "gray", lwd = 2)
abline(a = cf[1] + cf[3], b = cf[2], col = "black", lwd = 2)
legend("topleft", legend = c("male", "female"), col = c("black", "gray"), lwd = c(2, 2))
```
```{r}
head(cats)
```

```{r}
plot(cats$Hwt~cats$Bwt, col = c("brown3", "dodgerblue")[cats$Sex], pch = 20, xlab = "body weight", ylab = "heart weight")
legend("topleft", legend = c("female", "male"), pch = c(20, 20), col = c("brown3", "dodgerblue"))
```
```{r}
cats.fit <- lm(Hwt~Bwt+Sex, data = cats)
summary(cats.fit)
# y.hat = b0 + 4.08 * Bwt - 0.082 * Sex 
```
```{r}
# predict mean heart weight for female cat that weights 3.4kg 
xval <- data.frame(Bwt = c(3.4), Sex = c("F"))
predict(cats.fit, xval, interval = "prediction", level = 0.95)
```
```{r}
plot(cats$Hwt~cats$Bwt, col = c("brown3", "dodgerblue")[cats$Sex], pch = 20, xlab = "body weight", ylab = "heart weight")

cats.coef <- coef(cats.fit)
abline(a = cats.coef[1], b = cats.coef[2], col = "brown3", lwd = 2)
abline(a = cats.coef[1] + cats.coef[3], b = cats.coef[2], col = "dodgerblue", lwd = 2)
legend("topleft", legend = c("female", "male", "female fit", "male fit"), 
       pch = c(20, 20, NA, NA), col = c("brown3", "dodgerblue"), lwd = c(NA, NA, 2, 2))
```
```{r}
library(boot)
head(nuclear)
```
```{r}
pairs(nuclear)
```
```{r}
nuclear.fit1 <- lm(cost~t1+t2, data = nuclear)
summary(nuclear.fit1)
```
```{r}
nucler.fit2 <- lm(cost~t1+t2+date, data = nuclear)
summary(nucler.fit2)
```
```{r}
nuclear.fit3 <- lm(cost~date+cap+ne, data = nuclear)
summary(nuclear.fit3)
```
```{r}
confint(nuclear.fit3)
```
```{r}
df <- data.frame(Murders = c(8.6, 8.9, 8.52, 8.89, 13.07, 14.57, 21.36, 28.03, 31.49, 37.39, 46.26, 47.24, 52.33),
                 Police = c(260.35, 269.80, 272.04, 272.96, 272.51, 261.34, 268.89, 295.99, 319.87, 341.43, 356.59, 376.69, 390.19),
                 Unemployment = c(11, 7, 5.2, 4.3, 3.5, 3.2, 4.1, 3.9, 3.6, 7.1, 8.4, 7.7, 6.3),
                 Guns = c(178.15, 156.41, 198.02, 222.10, 301.92, 391.22, 665.56, 1131.21, 837.60, 794.9, 817.74, 583.17, 709.59))
df
```
```{r}
pairs(df)
```
```{r}
summary(lm(Murders~., data = df))
```
```{r}
summary(aov(Murders~., data = df))
```
```{r}
summary(lm(Murders~Police+Guns, data = df))
```
```{r}
xvals <- data.frame(Police = c(300, 300),
                    Guns = c(500, 0))
predict(lm(Murders~Police+Guns, data = df),
        xvals, interval = "confidence", level = 0.99)
```
```{r}
x <- seq(-4, 4, length.out = 100)
y <- x 
y2 <- x + x^2 
y3 <- x + x^2 + x^3

par(mfrow = c(1, 3))
plot(x, y, type = "l")
plot(x, y2, type = "l")
plot(x, y3, type = "l")
```
```{r}
head(mtcars)
```
```{r}
plot(mtcars$disp, mtcars$mpg)
```
```{r}
summary(lm(mpg~disp, data = mtcars))
```
```{r}
summary(lm(mpg~disp+I(disp^2), data = mtcars))
```
```{r}
summary(lm(mpg~disp+I(disp^2)+I(disp^3), data = mtcars))
```
```{r}
plot(mtcars$mpg~mtcars$disp)

xvals <- data.frame(disp = seq(min(mtcars$disp) - 50, max(mtcars$disp) + 50, length.out = 100))
pred1 <- predict(lm(mpg~disp, data = mtcars), xvals)
pred2 <- predict(lm(mpg~disp+I(disp^2), data = mtcars), xvals)
pred3 <- predict(lm(mpg~disp+I(disp^2)+I(disp^3), data = mtcars), xvals)
lines(xvals[,1], pred1, col = "brown", lwd = 2)
lines(xvals[,1], pred2, col = "brown", lty = 2, lwd = 2)
lines(xvals[,1], pred3, col = "brown", lty = 3, lwd = 2)
legend("topright", legend = c("linear", "quadratic", "cubic"), col = rep("brown", 3), lty = 1:3, lwd = rep(2, 3))
```
```{r}
plot(mtcars$mpg~mtcars$hp, col = c("brown3", "dodgerblue")[factor(mtcars$am)], pch = 20, cex = 1.5)
```
```{r}
car.log <- lm(mpg~log(hp)+am, data = mtcars)
summary(car.log)
```
```{r}
n <- 100
xvals <- seq(min(mtcars$hp) - 40, max(mtcars$hp) + 40, length.out = n)
df <- data.frame(hp = rep(xvals, 2),
                 am = rep(c(0, 1), each = n))
pred <- predict(car.log, df)

plot(mtcars$mpg~mtcars$hp, col = c("brown3", "dodgerblue")[factor(mtcars$am)], pch = 20, cex = 1.5)
lines(xvals, pred[1:n], col = "brown3")
lines(xvals, pred[(n+1):(n*2)], col = "dodgerblue")
legend("topright", legend = c("automatic", "manual"), col = c("brown", "dodgerblue"), pch = rep(20, 2))
```
```{r}
df <- data.frame(Init.Height = c(1000, 800, 600, 450, 300, 200, 100),
                 Dist = c(573, 534, 495, 451, 395, 337, 253))
plot(df$Dist~df$Init.Height)

# fitting order 2 polynomial to the data
df.fit.poly2 <- lm(Dist~Init.Height+I(Init.Height^2), data = df)
df.fit.poly3 <- lm(Dist~Init.Height+I(Init.Height^2)+I(Init.Height^3), data = df)
df.fit.poly4 <- lm(Dist~Init.Height+I(Init.Height^2)+I(Init.Height^3)+I(Init.Height^4), data = df)

xvals <- data.frame(Init.Height = seq(50, 1050, length.out = 1000))
pred.poly2 <- predict(df.fit.poly2, xvals)
pred.poly3 <- predict(df.fit.poly3, xvals)
pred.poly4 <- predict(df.fit.poly4, xvals)

lines(xvals[,1], pred.poly2, col = "brown")
lines(xvals[,1], pred.poly3, col = "brown", lty = 2)
lines(xvals[,1], pred.poly4, col = "brown", lty = 3)

legend("bottomright", legend = c("ord. 2", "ord. 3", "ord. 4"),
       col = rep("brown", 3), lty = 1:3)
```
```{r}
pred.poly3 <- predict(df.fit.poly3, xvals, interval = "confidence", level = 0.90)
plot(df$Dist~df$Init.Height)
lines(xvals[,1], pred.poly3[,1], col = "brown")
lines(xvals[,1], pred.poly3[,2], col = "brown", lty = 2)
lines(xvals[,1], pred.poly3[,3], col = "brown", lty = 2)
legend("bottomright", legend = c("best fit (ord. 3)", "90% CI"),
       col = rep("brown", 2), lty = 1:2)
```
```{r}
library(faraway)
head(trees)
```
```{r}
plot(trees$Volume~trees$Girth)
```
```{r}
trees.fit.quad <- lm(Volume~Girth+I(Girth^2), data = trees)
summary(trees.fit.quad)
```
```{r}
trees.fit.log <- lm(log(Volume)~log(Girth), data = trees)
summary(trees.fit.log)
```
```{r}
plot(trees$Volume~trees$Girth)

xvals <- data.frame(Girth = seq(7, 22, length.out = 1000))
trees.pred.quad <- predict(trees.fit.quad, xvals, interval = "prediction", level = 0.95)
trees.pred.log <- predict(trees.fit.log, xvals, interval = "prediction", level = 0.95)

lines(xvals[,1], trees.pred.quad[,1], col = "brown", lwd = 2)
lines(xvals[,1], trees.pred.quad[,2], col = "brown", lty = 2)
lines(xvals[,1], trees.pred.quad[,3], col = "brown", lty = 2)
lines(xvals[,1], exp(trees.pred.log[,1]), col = "darkgreen", lwd = 2)
lines(xvals[,1], exp(trees.pred.log[,2]), col = "darkgreen", lty = 2)
lines(xvals[,1], exp(trees.pred.log[,3]), col = "darkgreen", lty = 2)
legend("topleft", legend = c("quad. fit", "quad. 90% PI", "log-log fit", "log-log 90% PI"),
       col = rep(c("brown", "darkgreen"), each = 2), lty = rep(c(1, 2), 2),
       lwd = rep(c(2, 1), 2))
```
```{r}
head(mtcars)
```
```{r}
summary(lm(mpg~hp+wt+disp, data = mtcars))
```
```{r}
summary(lm(I(1/mpg)~hp+wt+disp, data = mtcars))
```
```{r}
head(diabetes)
```
```{r}
dia.fit <- lm(chol~age*frame, data = diabetes)
summary(dia.fit)
```
```{r}
dia.coef <- coef(dia.fit)
dia.coef
```
```{r}
dia.small <- c(dia.coef[1], dia.coef[2])
dia.med <- c(dia.coef[1] + dia.coef[3], dia.coef[2] + dia.coef[5])
dia.large <- c(dia.coef[1] + dia.coef[4], dia.coef[2] + dia.coef[6])
plot(diabetes$chol~diabetes$age,
     col = c("black", "darkgray", "lightgray")[diabetes$frame], pch = 20)
abline(dia.small, col = "black", lwd = 2)
abline(dia.med, col = "darkgray", lwd = 2)
abline(dia.large, col = "lightgray", lwd = 2)
legend("topright", legend = c("small frame", "medium frame", "large frame"),
       col = c("black", "darkgray", "lightgray"), lwd = rep(2, 3))
```
```{r}
warp.fit <- lm(breaks~wool*tension, data = warpbreaks)
summary(warp.fit)
```
```{r}
head(cats)
```
```{r}
cats.fit <- lm(Hwt~Bwt*Sex, data = cats)
summary(cats.fit)
```
```{r}
plot(cats$Hwt~cats$Bwt, col = c("brown", "dodgerblue")[cats$Sex], pch = 20, cex = 1)
cats.coef <- coef(cats.fit)
cats.female <- c(cats.coef[1], cats.coef[2])
cats.male <- c(cats.coef[1] + cats.coef[3], cats.coef[2] + cats.coef[4])
abline(cats.female, col = "brown", lwd = 2)
abline(cats.male, col = "dodgerblue", lwd = 2)
legend("topleft", legend = c("male", "female"), col = c("dodgerblue", "brown"), lwd = rep(2, 2))

xvals <- data.frame(Bwt = c(3.4), Sex = c("F"))
pred.pi <- predict(cats.fit, xvals, interval = "prediction", level = 0.95)
pred.ci <- predict(cats.fit, xvals, interval = "confidence", level = 0.95)
points(xvals[1,1], pred.pi[1], pch = 4, cex = 2)
lines(rep(xvals[1,1], 2), c(pred.pi[2], pred.pi[3]), lwd = 2, col = "gray")
lines(rep(xvals[1,1], 2), c(pred.ci[2], pred.ci[3]), lwd = 1.5)
lines(c(xvals[1,1] - 0.05, xvals[1,1] + 0.05), rep(pred.pi[2], 2), col = "gray", lwd = 2)
lines(c(xvals[1,1] - 0.05, xvals[1,1] + 0.05), rep(pred.pi[3], 2), col = "gray", lwd = 2)
lines(c(xvals[1,1] - 0.025, xvals[1,1] + 0.025), rep(pred.ci[2], 2), lwd = 1)
lines(c(xvals[1,1] - 0.025, xvals[1,1] + 0.025), rep(pred.ci[3], 2), lwd = 1)
```
```{r}
head(trees)
```
```{r}
summary(lm(Volume~Girth+Height, data = trees))
```
```{r}
summary(lm(Volume~Girth*Height, data = trees))
```
```{r}
summary(lm(log(Volume)~log(Girth)*log(Height), data = trees))
```
```{r}
head(mtcars)
```
```{r}
cars.fit <- lm(mpg~hp*factor(cyl)+wt, data = mtcars)
summary(cars.fit)
```
```{r}
xvals <- data.frame(hp = c(100, 210, 200), 
                    cyl = c(4, 8, 6),
                    wt = c(2.100, 3.900, 2.900))
pred <- predict(cars.fit, xvals, interval = "confidence", level = 0.95)
pred
```




