---
title: "R Notebook"
output: html_notebook
---

```{r}
# construct a 4 x 2 matrix that is filled with the values
# 4.3, 3.1, 8.2, 8.2, 3.2, 0.9, 1.6, 6.5
A <- matrix(c(4.3, 3.1, 8.2, 8.2, 3.2, 0.9, 1.6, 6.5), nrow = 4, ncol = 2)
A
```
```{r}
# confirm the dimension of the matix A is 3 x 2 when any one of its rows is removed
dim(A[-1,])
```
```{r}
# overwrite the second column of the matrix A with that same column sorted from smallest to largest
A[, 2] <- sort(A[, 2])
A
```
```{r}
# ensure that the returned value is a matrix when we delete the fourth row and the first column from A
matrix(A[-4, -1], ncol = 1)
```
```{r}
# store the bottom 4 elements of A as 2 x 2 matrix
B <- A[3:4,]
B
```
```{r}
# overwrite, in this order, the elements of A at positions (4,2), (1,2), (4,1), (1,1) with one half 
# of the two values on the diagonal of B
C <- A
C[c(4, 1), c(2, 1)] <- 0.5 * diag(x = B)
C
```
```{r}
# example of scalar multiplication and matrix subtraction
D <- cbind(c(1, 2, 7), c(2, 4, 6))
E <- cbind(c(10, 30, 50), c(20, 40, 60))
2/7 * (D - E)
```
```{r}
# examples of dot product
G <- matrix(c(1, 2, 7), ncol = 1) # 3 x 1 matrix
H <- matrix(c(3, 4, 8), ncol = 1) # 3 x 1 matrix

# G . H     - not possible 
# G^T . H   - result is 1 x 1
print(t(G) %*% H)

# H^T . (G . G^T)  - (1 x 3) . (3 x 3) -> result is 1 x 3
print(t(H) %*% (G %*% t(G)))

# (G . G^T) . B^T  - (3 x 3) . (1 x 3) -> not possible
```
```{r}
# confitm that A^-1 . A - I_4 produces 4 x 4 matrix of zeros
E <- rbind(c(2, 0, 0, 0), c(0, 3, 0, 0), c(0, 0, 5, 0), c(0, 0, 0, -1))
E

# solve - inverts a square, non-singular, matrix
# diag  - creates n x n identity matrix
solve(E) %*% E - diag(x = 4)
```

