---
title: "R Notebook"
output: html_notebook
---
```{r}
# what is the probability of observing a value five sigma or greater than the mean or more
1 - integrate(function(x) dnorm(x, 0, 1), -5, 5)$value
``` 
```{r}
# a fever is any temperature greater than 100.4 degrees Fahrenheit. What is the probability that the 
# patient has a fever given these observations 
tmp <- c(100.0, 99.8, 101.0, 100.5, 99.7)
m <- mean(tmp)
dev <- sd(tmp)

x <- seq(m - 10 * dev, m + 10 * dev, length.out = 1000)
plot(x, dnorm(x, m, dev), type = "l")
lines(rep(100.4, 2), c(0, 1), col = "darkgreen")
text(101.6, 0.2, "fever threshold", col = "darkgreen")

p <- integrate(function(x) dnorm(x, m, dev), 100.4, m + 10 * dev)$value
text(103, 0.1, paste("P(X > 100.4) =", format(p, 3)), col = "darkgreen")
```
```{r}
# what is the probability that the well is over 500m deep given that it takes x seconds for a coin tossed 
# inside to reach the bottom 
sec <- c(2.5, 3, 3.5, 4, 2)

# convert sec to dist: dist = 1/2 * 9.8 * time^2
dist <- 0.5 * 9.8 * sec ^ 2
m <- mean(dist)
dev <- sd(dist)

p <- integrate(function(x) dnorm(x, m, dev), 500, m + 100 * dev)
p
```
```{r}
# what is the probability that there is no well (depth of the well is 0)
p <- integrate(function(x) dnorm(x, m, dev), -1, 0)
p
```

